# Generated by Django 5.0.6 on 2024-06-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpresupuesto',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='formpresupuesto',
            old_name='producto',
            new_name='productos',
        ),
    ]
