# Generated by Django 5.0.6 on 2024-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_correo_formpresupuesto_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='slug',
        ),
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.TextField(default=5000),
        ),
    ]
