# Generated by Django 5.0.6 on 2024-06-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flan_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='precio',
            field=models.IntegerField(default=5000),
        ),
    ]
